# -*- coding: utf-8 -*-
"""nomes IBGE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jJe5FfQ4Uo8sbtYlVcTQh-8hw9SWc_vV
"""

import requests, json

nome = input("qual seu nome?")
localidade = 0 

while localidade < 1 or localidade > 2:
  localidade = int(input("voce selecionar uma localidade? \n 1) sim \n 2) não"))
  if localidade == 1:
    uf = input("qual UF voce deseja? \n 35) SP \n 33) RJ \n 31) MG")
    resultado = requests.get(f"https://servicodados.ibge.gov.br/api/v2/censos/nomes/{nome}?localidade={uf}")
  if localidade == 2:
    resultado = requests.get(f"https://servicodados.ibge.gov.br/api/v2/censos/nomes/{nome}")
  print('''
    Escolha um periodo de tempo:
    1) 1930    
    2) 1930 - 1940
    2) 1940 - 1950
    4) 1950 - 1960
    5) 1960 - 1970
    6) 1970 - 1980
    7) 1980 - 1990
    8) 1990 - 2000
    9) 2000 - 2010
  ''')  
  periodo = int(input("selelcione um periodo: ")) -1
  dados = json.loads(resultado.text)
  print(dados[0]["res"][periodo])